name: Scheduled build
on:
  schedule:
  # From CEST (UTC +2) 00:00 and 05:30 to UTC:
  - cron:  '40 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Netlify
      run: curl -s -X POST "https://api.vercel.com/v1/integrations/deploy/prj_AiTdcadB7QBFww57VPVTVoNXWgTO/GLCJSwNao9"
